name: learn
description: A new Flutter project.
 
publish_to: 'none'
 
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'
 
dependencies:
  flutter:
    sdk: flutter
 
  sizer: ^2.0.15
  device_preview: ^1.1.0
  get_it: ^7.2.0


  l10n:
    path: l10n
  statsfl: ^2.3.0
  flutter_bloc: ^8.1.1
  recase: ^4.1.0
  equatable: ^2.0.5
  fading_edge_scrollview: ^3.0.0
  shared_preferences: ^2.0.15
  flutter_svg: ^1.1.6
  dio: ^4.0.6
dev_dependencies:
  build_runner: ^2.2.0
 
 
 
flutter:
 
  uses-material-design: true

flutter_intl:
  enabled: true
  class_name: AppLocalization
  main_locale: en
  template-arb-file: l10n/lib/arb/intl_en.arb
  arb_dir: l10n/lib/arb
  output_dir: l10n/lib/generated